### ISSUE TITLE
Jetson Nano

### ISSUE THREAD

**Issue by ausil** [hrw/arm-socs-table#37]
**Describe the system**
(name like "Pine64 RockPro64", "Raspberry/Pi 4", url to vendor if possible, SoC name)
System name: Jetson Nano
Vendor name: Nvidia
SoC name: Tegra
URL to product page: https://developer.nvidia.com/embedded/jetson-nano-developer-kit

**Paste `/proc/cpuinfo` content**
```
processor	: 0
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 1

processor	: 1
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 1

processor	: 2
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 1

processor	: 3
BogoMIPS	: 38.40
Features	: fp asimd evtstrm aes pmull sha1 sha2 crc32 cpuid
CPU implementer	: 0x41
CPU architecture: 8
CPU variant	: 0x1
CPU part	: 0xd07
CPU revision	: 1
```

**Additional context**
Add any other information you want.

**Comment by binarymaster** [comment]
> SoC name: Tegra

According to [Wikipedia article](https://en.wikipedia.org/wiki/Nvidia_Jetson#Hardware), Jetson Nano uses a stripped-down version of Tegra X1.

You can probably name it `Tegra X1 Nano`.

Indeed the regular Tegra X1 cpuinfo dump (#39) has some differences.
