### ISSUE TITLE
Fix table left column

### ISSUE THREAD

**Issue by bkmgit** [hrw/arm-socs-table#41]
As the table is large, for readability, it may be helpful to fix the location of the [left column](https://www.w3docs.com/snippets/html/how-to-create-an-html-table-with-a-fixed-left-column-and-scrollable-body.html).

**Comment by bkmgit** [comment]
Can also use a [data tables extension](https://datatables.net/extensions/fixedcolumns/examples/initialisation/left_right_columns.html). Can implement if desired.

**Comment by hrw** [comment]
Oh, lovely!

When I started using DataTables (years ago with syscalls table project) it was either header or column.

If you know how to do it then I am all for accepting PR.

**Comment by bkmgit** [comment]
In the original pull request, the height of the table was fixed at 300px. Does this help?

**Comment by hrw** [comment]
300px is small subset of lines :(

**Comment by bkmgit** [comment]
But one can scroll vertically as well. Maybe 600px is better? 
On most screens, one cannot see the whole table without scrolling.
