### ISSUE TITLE
QEMU Max?

### ISSUE THREAD

**Issue by vielmetti** [hrw/arm-socs-table#66]
Are there any more details on how QEMU can be invoked to get the "max" list provided in this table?

I started at https://www.qemu.org/docs/master/system/target-arm.html and saw that there was a "-cpu max" option, but it wasn't at all clear from the docs how to force all of the advanced architecture support.

**Comment by hrw** [comment]
"max" cpu has all aarch64 cpu features enabled by default.

There are switches to add like "-cpu max,sve512=on,sme=off,lpa2=off" but I never remember their list.
