### ISSUE TITLE
Header of the table is not persistent when scrolling

### ISSUE THREAD

**Issue by Civil** [hrw/arm-socs-table#76]
Only part that is about SoC name is actually persistent when you are scrolling through the table.

See the screenshot included.

Issue is reproducible on Chrome and Safari

![image](https://user-images.githubusercontent.com/844380/212726491-20699056-8d34-4db5-9ced-4d3394b899dc.png)

**Comment by hrw** [comment]
It will stay that way. DataTables can not cope with header built from two rows and I decided to not fight with it.

You may use search field to limit amount of rows.

Check #41 and #59 for more.

**Comment by rossburton** [comment]
FWIW I noticed the header wasn't pinned and turned on fixedHeader and it just worked, so maybe this is fixed now?

https://datatables.net/extensions/fixedheader/ and `fixedHeader:true` appeared to do the right thing.
