### ISSUE TITLE
cpuinfo files automatically collected by sbc-bench

### ISSUE THREAD

**Issue by ThomasKaiser** [hrw/arm-socs-table#81]
Just FYI: here is a list of cpuinfo files (mostly) collected automatically by my sbc-bench script: https://github.com/ThomasKaiser/sbc-bench/tree/master/results/cpuinfo

The following files missing in your list all contain the `cpuid` flag and where kernel version is also listed, it's definitely collected directly on the machine by sbc-bench (some of the entries might be 'from the Internet' and added after double checking the contents carefully):

  * [Allwinner-A64-5.16.13-sunxi64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Allwinner-A64-5.16.13-sunxi64.cpuinfo)
  * [Allwinner-H6-5.7.0-rc6-geb17650.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Allwinner-H6-5.7.0-rc6-geb17650.cpuinfo)
  * [Allwinner-H616-5.15.18-sunxi64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Allwinner-H616-5.15.18-sunxi64.cpuinfo)
  * [Allwinner-R329-5.14.0-rc4-sun50iw11.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Allwinner-R329-5.14.0-rc4-sun50iw11.cpuinfo)
  * [Amlogic-A113X-5.9.16-jethubj100.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-A113X-5.9.16-jethubj100.cpuinfo)
  * [Amlogic-A311D-5.10.60-meson64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-A311D-5.10.60-meson64.cpuinfo)
  * [Amlogic-A311D2-5.4.125.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-A311D2-5.4.125.cpuinfo)
  * [Amlogic-S805X-5.10.60-meson64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-S805X-5.10.60-meson64.cpuinfo)
  * [Amlogic-S905-5.10.81-meson64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-S905-5.10.81-meson64.cpuinfo)
  * [Amlogic-S905D-5.0.2.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-S905D-5.0.2.cpuinfo)
  * [Amlogic-S905L2-5.15.55.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-S905L2-5.15.55.cpuinfo)
  * [Amlogic-S905W-5.9.0-arm-64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-S905W-5.9.0-arm-64.cpuinfo)
  * [Amlogic-S905X3-5.10.81-meson64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-S905X3-5.10.81-meson64.cpuinfo)
  * [Amlogic-S905Y2-5.15.2-meson64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-S905Y2-5.15.2-meson64.cpuinfo)
  * [Amlogic-S905Y4-5.4.125.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-S905Y4-5.4.125.cpuinfo)
  * [Amlogic-S912-5.9.0-arm-64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Amlogic-S912-5.9.0-arm-64.cpuinfo)
  * [Apple-M1-Pro-5.18.0-asahi.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Apple-M1-Pro-5.18.0-asahi.cpuinfo)
  * [BCM2387B0-5.16.7-bcm2711.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/BCM2387B0-5.16.7-bcm2711.cpuinfo)
  * [BCM2711B0-5.10.63-v8.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/BCM2711B0-5.10.63-v8.cpuinfo)
  * [Cavium-ThunderX-CN8890-5.16.0-rc2-00344-gc5c17547b778.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Cavium-ThunderX-CN8890-5.16.0-rc2-00344-gc5c17547b778.cpuinfo)
  * [HiSilicon-Kirin-620-4.19.5-hikey.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/HiSilicon-Kirin-620-4.19.5-hikey.cpuinfo)
  * [Marvell-Armada-3710-5.10.21-mvebu64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Marvell-Armada-3710-5.10.21-mvebu64.cpuinfo)
  * [Marvell-Armada-3720-5.10.21-mvebu64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Marvell-Armada-3720-5.10.21-mvebu64.cpuinfo)
  * [Mediatek-MT6762M-5.19.0-rc4+.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Mediatek-MT6762M-5.19.0-rc4+.cpuinfo)
  * [Mediatek-MT6762M-5.19.0-rc4.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Mediatek-MT6762M-5.19.0-rc4.cpuinfo)
  * [NXP-LS1028A-4.14.47-51091-g985a1f51c31c.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/NXP-LS1028A-4.14.47-51091-g985a1f51c31c.cpuinfo)
  * [Nexell-S5P6818-4.14.180-s5p6818.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Nexell-S5P6818-4.14.180-s5p6818.cpuinfo)
  * [Nvidia-Jetson-Nano-5.10.60-station.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Nvidia-Jetson-Nano-5.10.60-station.cpuinfo)
  * [Nvidia-Jetson-Orin-5.10.65-tegra.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Nvidia-Jetson-Orin-5.10.65-tegra.cpuinfo)
  * [RK3318-5.10.68-rockchip64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/RK3318-5.10.68-rockchip64.cpuinfo)
  * [RK3399-5.15.5-rockchip64.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/RK3399-5.15.5-rockchip64.cpuinfo)
  * [TI-J721E-5.10.100-g7a7a3af903.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/TI-J721E-5.10.100-g7a7a3af903.cpuinfo)
  * [Xilinx-XCZU9EG-5.4.0-1015-xilinx-zynqmp.cpuinfo](https://raw.githubusercontent.com/ThomasKaiser/sbc-bench/master/results/cpuinfo/Xilinx-XCZU9EG-5.4.0-1015-xilinx-zynqmp.cpuinfo)

**Comment by hrw** [comment]
Thanks! Will take a look at them.

**Comment by ThomasKaiser** [comment]
BTW: I don't know how comprehensive your SoC table should become but maybe it's useful to include stepping information from the start? As examples where this might matter:

  * Samsung's 'Mongoose 2 core' differs only by stepping but shares same core ID with Mongoose 1: [Exynos 8890](https://github.com/ThomasKaiser/sbc-bench/blob/master/results/cpuinfo/Exynos-8890-highperformance.cpuinfo) with Exynos-m1/r1p1 cores vs. [Exynos 8895](https://github.com/ThomasKaiser/sbc-bench/blob/master/results/cpuinfo/Exynos-8895.cpuinfo) containing Exynos-m1/r4p0 cores
  * Qualcomm's Krait line-up: [200/300/400/450 can't be differentiated by core ID alone only by looking at the stepping as well](https://github.com/Dr-Noob/cpufetch/blob/master/src/arm/uarch.c#L285-L293).

But since those are all things from the past and most probably more important for the SoC vendor's marketing department than anybody else...

**Comment by hrw** [comment]
There is a way - check X-Gene 1/2/3 cores or Cortex-A510.

But they differ more than just revision so it makes sense.

So for Exynos case it needs proper entry in data/cpu_cores.yml file with something like 0x1-4-0 for 'Exynos M2' and then import should use it.

Similar with Krait.

**Comment by ThomasKaiser** [comment]
BTW: when adding the various Allwinner SoCs (though they're all boring A53/r0p4 so `cpuinfo` reads identical on all of them with the only exception being count of cores) I would propose "URL to product page:" not pointing to Allwinner's site but to linux-sunxi wiki instead. Much more information that remains there in contrast to Allwinner themselves.

For an example: https://linux-sunxi.org/H6 vs. ... just realized that there are no individual links to SoCs on the Allwinner site any more :(

In case you plan to add SoCs from the above list I can send PRs. Just need to know whether `socs.yml` is adjusted manually (or by some script in some sort of 'backend') and which SoCs you want to choose.

**Comment by hrw** [comment]
I am open to any amount of SoCs. PR would be lovely (have some stuff to do at work).

So far there are no URLs to SoC pages (the only links in table are ones to Arm Technical Reference Manuals to Arm cores) and I do not plan any.

data/socs.yml is generated by import-cpuinfo.py which reads it using yaml library in Python and writes it back. If you want to do hand editing of that file then run it through import-cpuinfo.py at the end and compare results.

**Comment by ThomasKaiser** [comment]
Please check #83 whether ok or not.
