### ISSUE TITLE
cortex-a78c and cortex-x1c are documented  to support SSBS, despite the table indicating otherwise

### ISSUE THREAD

**Issue by markmi** [hrw/arm-socs-table#95]
Looking in:
arm_cortex_a78c_core_trm_102226_0002_03_en.pdf
arm_cortex_x1c_core_trm_101968_0002_04_en.pdf

There is the status-values:

"ID_AA64PFR1_EL1, AArch64"
"SBSS [7:4]
AArch64 provides the PSTATE.SSBS mechanism to mark regions that are Speculative Store
Bypassing Safe (SSBS).
0x01 AArch64 provides the PSTATE.SSBS mechanism to mark regions that are Speculative Store Bypassing Safe, but does not implement the MSR/MRS instructions to directly read and write the PSTATE.SSBS field."

"ID_PFR2_EL1, AArch32"
"SBSS [7:4]
1 AArch32 provides the PSTATE.SSBS mechanism to mark regions that are Speculative Store Bypassing Safe (SSBS)."

Also, other places in the documents indicate support for SSBS:

"The traps for EL0 and EL1 cache controls, PSTATE Speculative Store Bypass Safe (SSBS) bit and the
speculation barriers (CSDB, SSBB, PSSBB) instructions introduced in the Armv8.5‐A extension"

"The Cortex-X1C core implements the PSTATE Speculative Store Bypass Safe (SSBS) bit introduced in the Armv8.5‐A extension."

May be  linux only reports ssbs if the "MSR/MRS instructions" are supported?

Based on references in GCC sources and the like, such SSBS points may apply to a lot of other cortex contexts.

**Comment by hrw** [comment]
This table is built on what Linux reports, not what TRM reports for cpu cores used in SoC.

And those values can differ even between dumps from same SoC used in misc devices.

**Comment by markmi** [comment]
Hmm. Looks like Linux sometimes explicitly hides the SSBS feature based on some criteria if the investigative context involves kvm:
```
int kvm_hvc_call_handler(struct kvm_vcpu *vcpu)
{
	struct kvm_smccc_features *smccc_feat = &vcpu->kvm->arch.smccc_feat;
	u32 func_id = smccc_get_function(vcpu);
	u64 val[4] = {SMCCC_RET_NOT_SUPPORTED};
	u32 feature;
	gpa_t gpa;

	if (!kvm_hvc_call_allowed(vcpu, func_id))
		goto out;

	switch (func_id) {
	. . .
	case ARM_SMCCC_ARCH_FEATURES_FUNC_ID:
		feature = smccc_get_arg1(vcpu);
		switch (feature) {
		. . .
		case ARM_SMCCC_ARCH_WORKAROUND_2:
			switch (arm64_get_spectre_v4_state()) {
			case SPECTRE_VULNERABLE:
				break;
			case SPECTRE_MITIGATED:
				/*
				 * SSBS everywhere: Indicate no firmware
				 * support, as the SSBS support will be
				 * indicated to the guest and the default is
				 * safe.
				 *
				 * Otherwise, expose a permanent mitigation
				 * to the guest, and hide SSBS so that the
				 * guest stays protected.
				 */
				if (cpus_have_final_cap(ARM64_SSBS))
					break;
				fallthrough;
			case SPECTRE_UNAFFECTED:
				val[0] = SMCCC_RET_NOT_REQUIRED;
				break;
			}
			break;
. . .

static int get_kernel_wa_level(u64 regid)
{
	switch (regid) {
	. . .
	case KVM_REG_ARM_SMCCC_ARCH_WORKAROUND_2:
		switch (arm64_get_spectre_v4_state()) {
		case SPECTRE_MITIGATED:
			/*
			 * As for the hypercall discovery, we pretend we
			 * don't have any FW mitigation if SSBS is there at
			 * all times.
			 */
			if (cpus_have_final_cap(ARM64_SSBS))
				return KVM_REG_ARM_SMCCC_ARCH_WORKAROUND_2_NOT_AVAIL;
			fallthrough;
		case SPECTRE_UNAFFECTED:
			return KVM_REG_ARM_SMCCC_ARCH_WORKAROUND_2_NOT_REQUIRED;
		case SPECTRE_VULNERABLE:
			return KVM_REG_ARM_SMCCC_ARCH_WORKAROUND_2_NOT_AVAIL;
		}
		break;
. . .
```
It might be important to be sure data collection is via bare metal instead of kvm or to document that such issues of interpretation could be involved instead of directly being about the core itself.
